nohup ./E_chambre.sh &
nohup ./E_cuisine.sh &
nohup ./E_SDB.sh &
nohup ./E_salon.sh &
nohup ./E_SAM.sh &
nohup ./Pr_chambre.sh &
nohup ./Pr_cuisine.sh &
nohup ./PresenceSAM_ROS.sh &
nohup ./Pr_SDBdouche.sh &
nohup ./Volet_chambre.sh &
nohup ./courant_salon.sh &
nohup ./Volet_salon.sh &
nohup ./courant_microonde.sh &
nohup ./courant_refregerateur.sh &
